# Numpy (Numerical Python)

In [1]:
import numpy as np

In [2]:
# We use arrays in numpy, arrays do not exist in core python

In [3]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(np.array([1,2,3,4,5,6,7,8,9]))

numpy.ndarray

In [5]:
import array # Not useful that much and cannot be useful in data manipulation

In [6]:
array.array('i',[1,2,3,4,5,6,7,8,9])

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.array([1,34,56,67,'demo',.5])

array(['1', '34', '56', '67', 'demo', '0.5'], dtype='<U32')

In [8]:
np.array([1,34,56,67,'demo',.5],ndmin = 0)

array(['1', '34', '56', '67', 'demo', '0.5'], dtype='<U32')

In [9]:
np.array([1,34,56,67,'demo',.5],ndmin = 1)

array(['1', '34', '56', '67', 'demo', '0.5'], dtype='<U32')

In [10]:
np.array([1,34,56,67,'demo',.5],ndmin = 2)

array([['1', '34', '56', '67', 'demo', '0.5']], dtype='<U32')

In [11]:
# 0 dim --> 0 and 1 dim are the same
# 1 dim --> 0 and 1 dim are the same
# 2 dim --> row and column
# 3 dim --> x,y,z

In [12]:
np.array([1,34,56,67,'demo',.5],ndmin = 1).shape

(6,)

In [13]:
np.array([1,34,56,67,'demo',.5],ndmin = 2).shape

(1, 6)

In [14]:
np.array([1,34,56,67,'demo',.5],ndmin = 3).shape

(1, 1, 6)

In [15]:
np.array([1,34,56,67,'demo',.5],ndmin = 3)

array([[['1', '34', '56', '67', 'demo', '0.5']]], dtype='<U32')

In [16]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) # 3D array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])