In [60]:
# creating a matrix with output columns based on input vector(N)

import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [61]:
# #Similar matrix is created using np.vander function in numpy

import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [62]:
#  The determitant for both the matrixs is the same
np.linalg.det(matrix)

287.9999999999965

In [63]:
np.linalg.det(matrix1)

287.9999999999965

In [11]:
k = 3
sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = len(sequence)
print(f'Moving window is {k} and the number of elements is {n}')
print(f'The moving average sequence has {n-k+1} values')

Moving window is 3 and the number of elements is 13
The moving average sequence has 11 values


In [56]:
def movingWindow(lst,window):
    num = 0

    for i in range(len(lst)):
        print('y'+str(i),' ',(lst[num]+lst[num+1]+lst[num+2])/window,'=',lst[num],lst[num+1],lst[num+2])
        num+= 1
        if num == 11:
            break

In [57]:
movingWindow(sequence,k)

y0   5.0 = 3 5 7
y1   4.666666666666667 = 5 7 2
y2   5.666666666666667 = 7 2 8
y3   6.666666666666667 = 2 8 10
y4   9.666666666666666 = 8 10 11
y5   28.666666666666668 = 10 11 65
y6   49.333333333333336 = 11 65 72
y7   72.66666666666667 = 65 72 81
y8   84.0 = 72 81 99
y9   93.33333333333333 = 81 99 100
y10   116.33333333333333 = 99 100 150
